apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kevin@ibuqa.io
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
            podTemplate:
              spec:
                nodeSelector:
                  "kubernetes.io/os": linux
      - dns01:
          azureDNS:
            resourceGroupName: dns-zone
            subscriptionID: 82702432-2525-4259-bd45-ea9bda10908a
            hostedZoneName: ogaba.io
            environment: AzurePublicCloud
            managedIdentity:
              clientID: 0abbf17c-7485-42c4-b779-345f2ad9f9cf
